// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use pooler URL for queries
    url: process.env["DATABASE_URL"],
    // Use direct URL for migrations/DDL (Neon requires this for schema changes)
    // Note: directUrl is a valid Prisma feature but not yet in TypeScript types
    ...(process.env["DIRECT_URL"] && { directUrl: process.env["DIRECT_URL"] }),
  } as { url?: string; shadowDatabaseUrl?: string; directUrl?: string },
});
